version: "3.1"

services:
  db:
    image: mysql:9.2
    ports:
      - 3306:3306
    restart: no
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
    volumes:
      - ./migrations:/docker-entrypoint-initdb.d
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]

  adminer:
    image: adminer
    restart: no
    ports:
      - 8080:8080

  python:
    image: python-image
    volumes:
      - ./src:/src
    build:
      context: .
      dockerfile: ./src/Dockerfile
    ports:
      - 8000:8000
    environment:
      - MYSQL_HOST=db
      - MYSQL_DATABASE
      - MYSQL_USER
      - MYSQL_ROOT_PASSWORD
      - PORT:8000
    depends_on:
      db:
        condition: service_healthy
    restart: on-failure

volumes:
  migrations:
